FROM scratch

MAINTAINER bcessa <ben@datos.mx>

ADD htdocs/css /var/www/htdocs/css
ADD htdocs/images /var/www/htdocs/images
ADD htdocs/js /var/www/htdocs/js
ADD htdocs/favicon.ico /var/www/htdocs/favicon.ico
ADD htdocs/landing.html /var/www/htdocs/index.html

ADD htdocs/tsv.db /data/tsv.db

ADD tsv /

EXPOSE 7788

ENTRYPOINT ["/tsv", "server"]
